version: '3.7'
services:
  impala:
    container_name: impala
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/impala-kudu:latest
    external_links:
    - hadoop
    - hive
    - kudu-master
    - kudu-tserver
    - zookeeper
    ports:
    - 21000:21000
    - 21050:21050
    - 25000:25000
    - 25010:25010
    - 25020:25020
    environment:
      IMPALA_STATE_STORE: "false"
networks:
  parrot:
    name: parrot_default
    driver: bridge
